name:                HetrisV2
version:             0.1.0.0
github:              "VitorCBSB/HetrisV2"
license:             BSD3
author:              "Vitor Coimbra"
maintainer:          "vitorcoliveira91@gmail.com"
copyright:           "Vitor Coimbra"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Game

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/VitorCBSB/HetrisV2#readme>

executables:
  HetrisV2-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - lens
    - linear
    - sdl2
    - sdl2-mixer
    - sdl2-ttf
    - text
    - array
    - random
    - containers
